2025-08-07T19:34:51.599938547Z ==> Build successful ðŸŽ‰
2025-08-07T19:35:10.975858792Z ==> Deploying...
2025-08-07T19:35:36.832261041Z ==> Running 'cd src/backend && gunicorn main:app --bind 0.0.0.0:$PORT'
2025-08-07T19:35:43.241508005Z Redis not available - Cache disabled
2025-08-07T19:35:43.241545797Z Traceback (most recent call last):
2025-08-07T19:35:43.241553788Z   File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
2025-08-07T19:35:43.241624152Z     sys.exit(run())
2025-08-07T19:35:43.241632843Z              ^^^^^
2025-08-07T19:35:43.241636183Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2025-08-07T19:35:43.241824425Z     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2025-08-07T19:35:43.241830265Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
2025-08-07T19:35:43.241932972Z     super().run()
2025-08-07T19:35:43.241937602Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
2025-08-07T19:35:43.242037048Z     Arbiter(self).run()
2025-08-07T19:35:43.242118333Z     ^^^^^^^^^^^^^
2025-08-07T19:35:43.242122793Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
2025-08-07T19:35:43.24222608Z     self.setup(app)
2025-08-07T19:35:43.24223038Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup
2025-08-07T19:35:43.242308905Z     self.app.wsgi()
2025-08-07T19:35:43.242318136Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2025-08-07T19:35:43.242728141Z     self.callable = self.load()
2025-08-07T19:35:43.242737092Z                     ^^^^^^^^^^^
2025-08-07T19:35:43.242739952Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2025-08-07T19:35:43.242900632Z     return self.load_wsgiapp()
2025-08-07T19:35:43.242905393Z            ^^^^^^^^^^^^^^^^^^^
2025-08-07T19:35:43.242908763Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2025-08-07T19:35:43.242986478Z     return util.import_app(self.app_uri)
2025-08-07T19:35:43.242990898Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-07T19:35:43.242994108Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
2025-08-07T19:35:43.243161158Z     mod = importlib.import_module(module)
2025-08-07T19:35:43.243230533Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-07T19:35:43.243235923Z   File "/opt/render/project/python/Python-3.11.10/lib/python3.11/importlib/__init__.py", line 126, in import_module
2025-08-07T19:35:43.243318248Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-08-07T19:35:43.243377262Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-07T19:35:43.243453247Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2025-08-07T19:35:43.243457317Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2025-08-07T19:35:43.243459497Z   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2025-08-07T19:35:43.243461587Z   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2025-08-07T19:35:43.243463888Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2025-08-07T19:35:43.243465968Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2025-08-07T19:35:43.243468058Z   File "/opt/render/project/src/src/backend/main.py", line 40, in <module>
2025-08-07T19:35:43.243533852Z     app = create_app()
2025-08-07T19:35:43.243625168Z           ^^^^^^^^^^^^
2025-08-07T19:35:43.328998625Z   File "/opt/render/project/src/src/backend/main.py", line 27, in create_app
2025-08-07T19:35:43.379902342Z     from routes.recipes import recipes_bp
2025-08-07T19:35:43.379913003Z   File "/opt/render/project/src/src/backend/routes/recipes.py", line 2, in <module>
2025-08-07T19:35:43.379915143Z     from marshmallow import ValidationError
2025-08-07T19:35:43.379917374Z ModuleNotFoundError: No module named 'marshmallow'
2025-08-07T19:35:47.911072621Z ==> Exited with status 1
2025-08-07T19:35:48.054255074Z ==> Common ways to troubleshoot your deploy: https://render.com/docs/troubleshooting-deploys
2025-08-07T19:35:52.634852909Z ==> Running 'cd src/backend && gunicorn main:app --bind 0.0.0.0:$PORT'
2025-08-07T19:35:58.243485512Z Redis not available - Cache disabled
2025-08-07T19:35:58.243499603Z Traceback (most recent call last):
2025-08-07T19:35:58.243512244Z   File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
2025-08-07T19:35:58.24362251Z     sys.exit(run())
2025-08-07T19:35:58.243631181Z              ^^^^^
2025-08-07T19:35:58.243637891Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2025-08-07T19:35:58.243733207Z     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2025-08-07T19:35:58.243760409Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 236, in run
2025-08-07T19:35:58.243894407Z     super().run()
2025-08-07T19:35:58.243917259Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
2025-08-07T19:35:58.244024896Z     Arbiter(self).run()
2025-08-07T19:35:58.244053767Z     ^^^^^^^^^^^^^
2025-08-07T19:35:58.244057547Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 58, in __init__
2025-08-07T19:35:58.244155614Z     self.setup(app)
2025-08-07T19:35:58.244188786Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 118, in setup
2025-08-07T19:35:58.244288172Z     self.app.wsgi()
2025-08-07T19:35:58.244292962Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2025-08-07T19:35:58.244404569Z     self.callable = self.load()
2025-08-07T19:35:58.24442078Z                     ^^^^^^^^^^^
2025-08-07T19:35:58.244424901Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2025-08-07T19:35:58.244526597Z     return self.load_wsgiapp()
2025-08-07T19:35:58.244531097Z            ^^^^^^^^^^^^^^^^^^^
2025-08-07T19:35:58.244534568Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2025-08-07T19:35:58.244676346Z     return util.import_app(self.app_uri)
2025-08-07T19:35:58.244691627Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-07T19:35:58.244696658Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
2025-08-07T19:35:58.244859728Z     mod = importlib.import_module(module)
2025-08-07T19:35:58.244870378Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-07T19:35:58.244873869Z   File "/opt/render/project/python/Python-3.11.10/lib/python3.11/importlib/__init__.py", line 126, in import_module
2025-08-07T19:35:58.244993126Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-08-07T19:35:58.245038909Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-07T19:35:58.245041839Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2025-08-07T19:35:58.245043639Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2025-08-07T19:35:58.245045289Z   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2025-08-07T19:35:58.245047009Z   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2025-08-07T19:35:58.24505369Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2025-08-07T19:35:58.24505672Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2025-08-07T19:35:58.24505984Z   File "/opt/render/project/src/src/backend/main.py", line 40, in <module>
2025-08-07T19:35:58.245176438Z     app = create_app()
2025-08-07T19:35:58.245184068Z           ^^^^^^^^^^^^
2025-08-07T19:35:58.24521062Z   File "/opt/render/project/src/src/backend/main.py", line 27, in create_app
2025-08-07T19:35:58.245291895Z     from routes.recipes import recipes_bp
2025-08-07T19:35:58.245307916Z   File "/opt/render/project/src/src/backend/routes/recipes.py", line 2, in <module>
2025-08-07T19:35:58.245395451Z     from marshmallow import ValidationError
2025-08-07T19:35:58.245403232Z ModuleNotFoundError: No module named 'marshmallow'